[build]
  base = "pp-dev"                     # Set the base directory to the subdirectory where your app is located
  command = "npm run build"           # Run the build command from within the base directory
  publish = ".next"                   # The publish directory relative to the base directory

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Optional: Use the Next.js plugin for better integration

